### ISSUE TITLE
How do classifiers work?

### ISSUE THREAD

**Issue by reobroqn** [mirand863/hiclass#31]
Thanks for your repo!
I'm working on a dataset with a hierarchical multi-label structure, the depth is only 2: rootnode -> node1 -> node2.
I read your evaluation code. I found it in the paper you mentioned, it does make sense to me.
But I'm curious about how the classifiers work or they are just like their names? 
Could you share some references or anything related to it?

Thank you,

**Comment by mirand863** [comment]
Hi @reobroqn,

It is a great question. I am currently writing more documentation and I will be explaining there how the current implementations work. I will let you know once I release the new documentation on read the docs.

Kind regards,
Fabio

**Comment by mirand863** [comment]
Hello @reobroqn,

I finally finished updating the documentation. Here are the explanations on how the classifiers work: [https://hiclass.readthedocs.io/en/latest/algorithms/index.html](https://hiclass.readthedocs.io/en/latest/algorithms/index.html)

Please, let me know if anything is not clear so I can improve the documentation.

Kind regards,
Fabio

**Comment by mirand863** [comment]
Hi @reobroqn,

I am closing this issue, but again please let me know if anything is not clear on the online documentation at https://hiclass.readthedocs.io/en/latest/algorithms/index.html so I can reopen the issue.

Kind regards,
Fabio
