### ISSUE TITLE
Python >= 3.9 support

### ISSUE THREAD

**Issue by flo-ri-an** [mirand863/hiclass#35]
Hi

First of all, really like your implementation of hierarchical classifiers. Bravo. I am constrained by other package requirements to have python >= 3.9.

Would it be possible to bump the python version requirements or is there any major blocker for this?

**Comment by mirand863** [comment]
Hi @flo-ri-an 

Thanks for the interest in HiClass. One of the dependencies, Ray, was incompatible with Python 3.9 a couple of months ago but it seems that it is compatible now. Will give it a try and let you know if it works.

Kind regards,
Fabio

**Comment by mirand863** [comment]
Fortunately it worked with python 3.9 now. With python 3.10 it cannot find any installation candidate for Ray so at least for now not possible.

**Comment by flo-ri-an** [comment]
Cool, thank you so much for the fast update!
