### ISSUE TITLE
Single predictions have unexpected format: ["['level_0", "level_1"]"]

### ISSUE THREAD

**Issue by flo-ri-an** [mirand863/hiclass#44]
**Describe the bug**
When using the LCPN algorithm, I receive an unexpected format for predictions: A 1d ndarray with a single element, the list of nodes wrapped in a string.

I get:
```{python}
["['level_0', 'level_1', 'level_2']"]
```

I expect:
```{python}
['level_0', 'level_1', 'level_2']
```

**To Reproduce**
1. Train an LCPN model
2. Feed it a single example for prediction

**Expected behavior**
Previously, if I recall correctly, I would have receive a single list of the predicted branch.

**Desktop (please complete the following information):**
 - OS: Ubuntu 21.10 (GNU/Linux 5.13.0-1033-gcp x86_64
 - Version 4.1.1

**Comment by mirand863** [comment]
Hi @flo-ri-an,

Thank you for reporting this issue. I will take a look into it and get back to you shortly.

Kind regards,
Fabio

**Comment by mirand863** [comment]
Hi @flo-ri-an,

Sorry for the delay. I prepared the following example to try to reproduce the issue:

```python
from hiclass import LocalClassifierPerNode
from sklearn.ensemble import RandomForestClassifier

# Define data
X_train = [[1], [2], [3], [4]]
Y_train = [
    ['Animal', 'Mammal', 'Sheep'],
    ['Animal', 'Mammal', 'Cow'],
    ['Animal', 'Reptile', 'Snake'],
    ['Animal', 'Reptile', 'Lizard'],
]

# Use random forest classifiers for every node
rf = RandomForestClassifier()
classifier = LocalClassifierPerNode(local_classifier=rf)

# Train local classifier per node
classifier.fit(X_train, Y_train)

# Predict
X_test = [[4], [3], [2], [1]]
predictions = classifier.predict(X_test)
print("Normal predictions")
print(predictions)

# Buggy prediction
X_test_buggy = [[4]]
buggy_predictions = classifier.predict(X_test_buggy)
print("Buggy predictions")
print(buggy_predictions)
```

This script produces the following output:

```python
>>> Normal predictions
>>> [['Animal' 'Reptile' 'Lizard']
     ['Animal' 'Reptile' 'Snake']
     ['Animal' 'Mammal' 'Cow']
     ['Animal' 'Mammal' 'Sheep']]
>>> Buggy predictions
>>> [['Animal' 'Reptile' 'Lizard']]
```

The expected output should be `['Animal' 'Reptile' 'Lizard']`. Is that correct?

**Comment by mirand863** [comment]
@flo-ri-an Just a quick update... I created pull request #47 to fix this issue. Now this is the prediction for the example above:

```python
Normal predictions
[['Animal' 'Reptile' 'Lizard']
 ['Animal' 'Reptile' 'Snake']
 ['Animal' 'Mammal' 'Cow']
 ['Animal' 'Mammal' 'Sheep']]
Buggy predictions
['Animal' 'Reptile' 'Lizard']
```
Just waiting for your confirmation to make sure if I understood it correctly.

**Comment by flo-ri-an** [comment]
@mirand863, thanks a lot for your work on this.

Now, in the meantime I gave it some more consideration.

What mostly intrigued me was the fact that the predicted branch was wrapped as a string. I had code written against an older version of hiclass that returned a list/ndarray representing the branch.

Looking at the standard return value for scikit-learn's `predict()`, it usually returns `ndarray(n_samples)` or `ndarray(n_samples, n_classes)` for multiclass. Now hiclass falls somewhere in between, depending on how you want to define the branch that it predicts.

To stay scikit-learn compliant, you should probably always return an `ndarray` containing the prediction, even if it was a single sample. Like:
```{python}
>>> Buggy predictions
>>> [['Animal' 'Reptile' 'Lizard']]

```

**Comment by mirand863** [comment]
> @mirand863, thanks a lot for your work on this.
> 
> Now, in the meantime I gave it some more consideration.
> 
> What mostly intrigued me was the fact that the predicted branch was wrapped as a string. I had code written against an older version of hiclass that returned a list/ndarray representing the branch.
> 
> Looking at the standard return value for scikit-learn's `predict()`, it usually returns `ndarray(n_samples)` or `ndarray(n_samples, n_classes)` for multiclass. Now hiclass falls somewhere in between, depending on how you want to define the branch that it predicts.
> 
> To stay scikit-learn compliant, you should probably always return an `ndarray` containing the prediction, even if it was a single sample. Like:
> 
> ```
> >>> Buggy predictions
> >>> [['Animal' 'Reptile' 'Lizard']]
> ```

I also think that the prediction should still be a 2D ndarray, even if only a single example is predicted. However, I am not sure what could possibly cause the prediction to be wrapped in a string. Can you please provide a minimal working example?

**Comment by flo-ri-an** [comment]
I'm really sorry for reporting this in the first place. Maybe it'll help to bring about a change that would certainly come in handy.

But first of all, this is not a **bug**.

I had written a transformer that does upsampling for underrepresented minority classes. This transformer returned dataframes for both the features and target. Downstream in my pipeline, I have the `hiclass` classifier. Because it was fed data frames, the targets somehow all ended up being wrapped in strings.

Hence, I probably really only trained the root node for the last couple of days :homer_simpson_doh:

So, please just forget about this. It never was an issue. *But*, it might be an opportunity to make classifiers accept `pd.DataFrame`s as well.

**Comment by mirand863** [comment]
It is OK, there is no need to apologize. Dataframes are converted to numpy arrays by a function provided by scikit-learn, but I also have problems with it sometimes and it only gets the headers of the dataframes. Perhaps this is what happened in your case? A simple `np.array(df)` before calling `fit` and `predict` would probably solve your problem, but I can also add that before calling the function from scikit-learn.
