### ISSUE TITLE
Add actual link to Arxiv article in readme

### ISSUE THREAD

**Issue by impredicative** [mirand863/hiclass#69]
In the Citation section of the Readme, perhaps the actual hyperlink to https://arxiv.org/abs/2112.06560 can be added.

**Comment by mirand863** [comment]
@impredicative,

Thank you for the great suggestion! Just added a hyperlink in the text and the DOI for bibtex as well. Now the README looks like this:

## Citation

If you use HiClass in your research, please cite our [preprint on arXiv](https://arxiv.org/abs/2112.06560):

> Miranda, Fábio M., Niklas Köehnecke, and Bernhard Y. Renard. "HiClass: a Python library for local hierarchical classification compatible with scikit-learn." arXiv preprint arXiv:2112.06560 (2021).

```latex
@article{miranda2021hiclass,
  title={HiClass: a Python library for local hierarchical classification compatible with scikit-learn},
  author={Miranda, F{\'a}bio M and K{\"o}ehnecke, Niklas and Renard, Bernhard Y},
  journal={arXiv preprint arXiv:2112.06560},
  year={2021},
  doi = {arXiv:2112.06560},
  url = {https://arxiv.org/abs/2112.06560}
}
```

**Note**: If you use HiClass in your GitHub projects, please add `hiclass` in the `requirements.txt`.

In addition, we would like to list publications that use HiClass to solve hierarchical problems. If you would like your manuscript to be added to this list, please email the reference, the name of your lab, department and institution to fabio.malchermiranda@hpi.de
